development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>